### ISSUE TITLE
KeyError when updating records (ok when creating) 

### ISSUE THREAD

**Issue by tpcc20** [fopina/django-bulk-update-or-create#23]
I've been implementing this into my project and the creation part works great and update works great on certain tables.

But im getting this error when I implemented it in one portion of my site
```

[2021-07-13 18:04:17,637: ERROR/MainProcess] Task project.tasks.update_all[d4695e9e-81e4-4807-9f98-bffd1ef7ada3] raised unexpected: KeyError(('BLUE2', 10157121))
Traceback (most recent call last):
  File "c:\users\user\documents\repos\project\venv\lib\site-packages\celery\app\trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "c:\users\user\documents\repos\project\venv\lib\site-packages\celery\app\trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "C:\Users\user\Documents\project\tasks.py", line 1276, in update_all
    import_new_items(source_system)
  File "C:\Users\user\Documents\project\tasks.py", line 918, in import_new_items
    BlueItems.objects.bulk_update_or_create(to_import,['unique_id',
  File "c:\users\user\documents\repos\project\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\user\documents\repos\project\venv\lib\site-packages\bulk_update_or_create\query.py", line 65, in bulk_update_or_create
    return r
  File "c:\users\user\documents\repos\project\venv\lib\site-packages\bulk_update_or_create\query.py", line 152, in __bulk_update_or_create
    for to_u in to_update:
KeyError: ('BLUE2', 10157121)
```

I am using a MySQL database. I am matching on two fields. BLUE2 is a varchar field and 10157121 is an int column.

It works perfectly when its a clean database with no records and it creates for the first time.

**Comment by fopina** [comment]
can you show the output for `pip freeze | grep bulk`? that seems like a bug that was fixed in a previous version

**Comment by tpcc20** [comment]
Thank you for getting back to me so quick! I really appreciate it!
I pip installed it yesterday so it should be the most up to date version.


`django-bulk-update-or-create==0.3.0`

**Comment by fopina** [comment]
can you share model definition and the bulk line?

**Comment by tpcc20** [comment]
Ah you helped me realize it was user error.

The fields I was specifying to insert/update didn't include the fields listed in the match_field parameter. 

Thank you!

**Comment by fopina** [comment]
Hmm you shouldn't need to include match_field in the update_fields.. can you share the example?
